{
  "uid" : "8c990c026b3952ef",
  "name" : "recognize trusted forwarder",
  "fullName" : "Contract: ERC2771Context.recognize trusted forwarder",
  "historyId" : "c3956d54d6afe498dbd01c6aa8753891",
  "time" : {
    "start" : 1635554804068,
    "stop" : 1635554804660,
    "duration" : 592
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be7f490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be7f490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/metatx/ERC2771Context.test.js:19:48)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: ERC2771Context"
  }, {
    "name" : "testClass",
    "value" : "Contract: ERC2771Context"
  }, {
    "name" : "testMethod",
    "value" : "recognize trusted forwarder"
  }, {
    "name" : "package",
    "value" : "Contract: ERC2771Context"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "8c990c026b3952ef.json",
  "parameterValues" : [ ]
}